; Definitations for ATMEGA328PB

.EQU POB_REG = 0x25 ; Register addresses for ports, to be used in an
.EQU POC_REG = 0x28 ; array of ports
.EQU POD_REG = 0x2B
.EQU POE_REG = 0x2E

.EQU PIB_REG = 0x23
.EQU PIC_REG = 0x26
.EQU PID_REG = 0x29
.EQU PIE_REG = 0x2C

; ----- SPI COMMS ----------------
; Compatible with 88/168/328P
.EQU SPI_SS_GPIO 	= PORTB2
.EQU SPI_SS_PORT 	= PORTB
.EQU SPI_SS_PIN		= PINB
.EQU SPI_SS_DDR 	= DDRB

.EQU SPI_MOSI_GPIO	= PORTB3
.EQU SPI_MOSI_PORT	= PORTB
.EQU SPI_MOSI_PIN	= PINB
.EQU SPI_MOSI_DDR 	= DDRB

.EQU SPI_MISO_GPIO 	= PORTB4
.EQU SPI_MISO_PORT 	= PORTB
.EQU SPI_MISO_PIN 	= PINB
.EQU SPI_MISO_DDR 	= DDRB

.EQU SPI_SCK_GPIO 	= PORTB5
.EQU SPI_SCK_PORT	= PORTB
.EQU SPI_SCK_PIN 	= PINB
.EQU SPI_SCK_DDR 	= DDRB

; ----- I2C COMMS ----------------
; Compatible with 88/168/328P
.EQU I2C_PORT	 	= PORTC
.EQU I2C_PIN		= PINC
.EQU I2C_DDR		= DDRC
.EQU I2C_SDA_GPIO	= PORTC4
.EQU I2C_SCL_GPIO	= PORTC5

; ----- SERIAL COMMS -------------
; Compatible with 88/168/328P
.EQU USART_TX_GPIO	= PORTD1
.EQU USART_TX_PORT 	= PORTD
.EQU USART_TX_DDR 	= DDRD
.EQU USART_RX_GPIO	= PORTD0
.EQU USART_RX_PIN 	= PIND
.EQU USART_RX_DDR 	= DDRD

; Additional ports (not found on P version of chip)

.EQU SPI_SS1_GPIO	= PORTE2
.EQU SPI_SS1_PORT	= PORTE
.EQU SPI_SS1_PIN	= PINE
.EQU SPI_SS1_DDR	= DDRE

.EQU SPI_MOSI1_GPIO = PORTE3
.EQU SPI_MOSI1_PORT = PORTE
.EQU SPI_MOSI1_PIN	= PINE
.EQU SPI_MOSI1_DDR	= DDRE

.EQU SPI_MISO1_GPIO = PORTC0
.EQU SPI_MISO1_PORT = PORTC
.EQU SPI_MISO1_PIN	= PINC
.EQU SPI_MISO1_DDR	= DDRC

.EQU SPI_SCK1_GPIO	= PORTC1
.EQU SPI_SCK1_PORT	= PORTC
.EQU SPI_SCK1_PIN 	= PINC
.EQU SPI_SCK1_DDR 	= DDRC

.EQU I2C1_PORT	 	= PORTE
.EQU I2C1_PIN		= PINE
.EQU I2C1_DDR		= DDRE
.EQU I2C1_SDA_GPIO	= PORTE0
.EQU I2C1_SCL_GPIO	= PORTE1
