
.EQU POB_REG = 0x25 ; Register addresses for ports, to be used in an
.EQU POC_REG = 0x28 ; array of ports
.EQU POD_REG = 0x2B

.EQU PIB_REG = 0x23
.EQU PIC_REG = 0x26
.EQU PID_REG = 0x29

; ----- SPI COMMS ----------------

.EQU SPI_SS_GPIO = PB2
.EQU SPI_SS_PORT = PORTB
.EQU SPI_SS_PIN = PINB
.EQU SPI_SS_DDR = DDRB

.EQU SPI_MOSI_GPIO = PB3
.EQU SPI_MOSI_PORT = PORTB
.EQU SPI_MOSI_PIN = PINB
.EQU SPI_MOSI_DDR = DDRB

.EQU SPI_MISO_GPIO = PB4
.EQU SPI_MISO_PORT = PORTB
.EQU SPI_MISO_PIN = PINB
.EQU SPI_MISO_DDR = DDRB

.EQU SPI_SCK_GPIO = PB5
.EQU SPI_SCK_PORT = PORTB
.EQU SPI_SCK_PIN = PINB
.EQU SPI_SCK_DDR = DDRB

; ----- I2C COMMS ----------------
.EQU I2C_PORT = PORTC
.EQU I2C_PIN = PINC
.EQU I2C_DDR = DDRC
.EQU I2C_SDA_GPIO = PC4
.EQU I2C_SCL_GPIO = PC5

; ----- SERIAL COMMS -------------
.EQU USART_TX_GPIO = PD1
.EQU USART_TX_PORT = PORTD
.EQU USART_TX_DDR = DDRD
.EQU USART_RX_GPIO = PORTD0
.EQU USART_RX_PIN = PIND
.EQU USART_RX_DDR = DDRD
